node {
   def mvnHome
   stage('Preparation') { // for display purposes
      // Get some code from a GitHub repository
      git 'https://github.com/vvsrk/DevOps.git'
      // Get the Maven tool.
      // ** NOTE: This 'M3' Maven tool must be configured
      // **       in the global configuration.           
      mvnHome = tool 'M3'
   }
   stage('Build') {
  sh "echo \'\n============!!!!!!!======'"
  sh "pwd"

      // Run the maven build
      if (isUnix()) {
           sh "'${mvnHome}/bin/mvn' -f maven-webapp/pom.xml clean install"

         //sh "'${mvnHome}/bin/mvn' clean"
      } else {
         bat(/"${mvnHome}\bin\mvn" -Dmaven.test.failure.ignore clean package/)
      }
   }
   
}